### ISSUE TITLE
Find interest regions with DoG

### ISSUE THREAD

**Issue by Queuecumber** [CS598TeamAwesome/Project2-LocalDescriptorAndBagOfFeature#1]
Use a difference of guassians to find interest regions

@chengliu22 should support @SoulCalculator work

**Comment by SoulCalculator** [comment]
Got it.

**Comment by chengliu22** [comment]
I also find a useful website to do SIFT using opencv. Send you later.

XIAORAN LIU notifications@github.com于2014年3月2日星期日写道：

**Comment by chengliu22** [comment]
Hey gays,
Go for this website. I think this is useful for this part.
http://docs.opencv.org/doc/user_guide/ug_features2d.html#features2d

**Comment by whyamialive** [comment]
So for this part, OpenCV DOES NOT have a Difference of Gaussians you can call directly. But OpenCV DOES have functions for getting Gaussian kernels. So to do a DoG you just filter with two Gaussian kernels with different sigma values and take the difference.

This applies specifically for SIFT feature detection and extraction.

**Comment by whyamialive** [comment]
For feature detection, we also need to implement an approach using a regular grid (much easier) and compare the two approaches (regular grid vs interest regions).

The regular grid method is very straightforward, so that might be a good place to start if you need to get something working in a short amount of time.

**Comment by chengliu22** [comment]
Hi Paul,
Could you see the link I sent on GitHub? Is the code useful for this
project?

Paul Ton notifications@github.com于2014年3月5日星期三写道：

**Comment by SoulCalculator** [comment]
Really sorry for replying late guys, I'm recently struggling with my another courses, hopefully I can get some outcomes within these two days, if I get stuck I'll let you guys know asap.

**Comment by chengliu22** [comment]
Hi all,
I upload a test program to extract features. I don't know if it is good for
this part. Please give me some suggestions.

Cheng

XIAORAN LIU notifications@github.com于2014年3月5日星期三写道：

**Comment by whyamialive** [comment]
Hi, Cheng:

Unfortunately, that is OpenCV's complete implementation of our assignment. We are supposed to write our own code to do the same thing (or something similar). We CAN use OpenCV's built in Gaussian filter and kernel methods.

(This is similar to how in Project1 we were supposed to write our own K-means and Convolution implementation, even though OpenCV already has built in kmeans and convolve).

**Comment by whyamialive** [comment]
The good news is that the code you found and wrote will be useful for us to both compare with what we develop and also help us test later steps.

**Comment by chengliu22** [comment]
But I find that in the description of this project, Prof Hua indicate that
you don't need to implement code for extracting local image descriptors.
Instead my use the build-in function in opencv. Does that mean we can use
detector in opencv as I wrote?

**Comment by whyamialive** [comment]
Oh. That's a good point. I don't know the answer to that. Send an email to the professor and see what he says about it.

**Comment by whyamialive** [comment]
Yeah, I'm looking at some of OpenCV's feature detectors and I think you are right. It would be too much work for us to re-implement each one of those ourselves. (Still send the email to double check).

Anyway, the next step for you would be to use it to gather all the features descriptors for a set of images (let's use the Graz02 set from the assignment). Once we have all the feature descriptors we can continue to the later steps (clustering, training the vocabulary, quantizing, etc).

Also, I see that you are using SURF. You can also do the same thing with SIFT (from Max's link in #3) and maybe FAST. (the usage for those look identical so that might be easy). And I guess we can do tests on those three to compare them.

**Comment by SoulCalculator** [comment]
I created 5 temp Mat to calculate the dog, and modified the filter matrix to 7 X 7 with Gaussian filter value from 1.0 to 16.0 (doubled each time), so far I think this is the best result I got, I still confused about how to set the matrix value and decide the filter value, I'm not sure this value set will work perfect on every image, or maybe we need to do some experiments.

**Comment by whyamialive** [comment]
If you are having trouble reading your emails or the rest of this thread, we don't have to calculate Difference of Gaussians ourselves for this task. We can use OpenCV's feature detectors directly, so you don't need to worry about Gaussian filters anymore.

The goal of this task and #3 together now becomes to gather all the feature descriptors for a set of images using the method that Cheng demonstrated. We want to be able to do this with a few different detection methods (at the very least SIFT, which uses DoG,  and Dense, which is a regular grid).

**Comment by SoulCalculator** [comment]
Oops I missed several emails...

**Comment by SoulCalculator** [comment]
What kind of data structure you guys need from #1  for the other parts of the project besides the image?

**Comment by chengliu22** [comment]
And also from #3

XIAORAN LIU notifications@github.com于2014年3月10日星期一写道：

**Comment by Queuecumber** [comment]
You can use BagOfFeatures from Util/Types.hpp which is just a
vector<vector<double>>

e.g. a vector of histograms (or SIFT descriptors)

Max
