### ISSUE TITLE
K-Means

### ISSUE THREAD

**Issue by Queuecumber** [CS598TeamAwesome/Project2-LocalDescriptorAndBagOfFeature#2]
Implement K-Means clustering algorithm

@Queuecumber will support this work as well

**Comment by whyamialive** [comment]
Committed a working, bare-bone implementation of K-means.

Forthcoming enhancements that will help us include:
- random distribution and multiple run
- compactness measure for evaluating which run is the best
- early termination for long-running cases
- hierarchical k-means

Further enhancements that we probably won't have time for:
- KD Trees
- parallelization of trials
- parallelization of within cluster processing
- smarter fixed distribution strategies

**Comment by Queuecumber** [comment]
Awesome you're well ahead of schedule here
