### ISSUE TITLE
Extract Features from Interest Regions

### ISSUE THREAD

**Issue by Queuecumber** [CS598TeamAwesome/Project2-LocalDescriptorAndBagOfFeature#3]
Use algorithm from #1 and extract features

@chengliu22 should work with @anlegong on this, @SoulCalculator can support their work with his work on #1

**Comment by Queuecumber** [comment]
Use [this](http://docs.opencv.org/trunk/doc/py_tutorials/py_feature2d/py_sift_intro/py_sift_intro.html) (written for python but should directly convert to C++) so extract the SIFT keypoints

**Comment by chengliu22** [comment]
Hi all,
I just upload a test file to extract features. I don't if it is fine for this part. Please give me some suggestions.

Cheng
