### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by Queuecumber** [CS598TeamAwesome/Project2-LocalDescriptorAndBagOfFeature#7]
Everyone should design test cases for their parts and provide a systematic way of integrating

**Comment by whyamialive** [comment]
Different Settings:
- vary the detection method (Sift, Dense)
- vary the descriptor extractor (Sift, raw?)
- vary the quantization (HardAssignment, CodewordUncertainty)
- Train GMM and use supervectors

Different Datasets:
- Scene15: http://www-cvr.ai.uiuc.edu/ponce_grp/data/ [1]
- Caltech101: http://www.vision.caltech.edu/feifeili/Datasets.htm
  [2]

**Comment by whyamialive** [comment]
some preliminary results:
https://docs.google.com/spreadsheet/ccc?key=0AiLEOuaMRmmAdGY0UDd6R2ZBdUNTakdqWjRTalNhSnc&usp=sharing
